const ACTIVITY_TYPES = {
  PROJECT_CREATED: 'PROJECT_CREATED',
  PROJECT_UPDATED: 'PROJECT_UPDATED',
  PROJECT_DELETED: 'PROJECT_DELETED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_MOVED: 'TASK_MOVED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_DELETED: 'TASK_DELETED',
  MEMBER_JOINED: 'MEMBER_JOINED',
};

module.exports = { ACTIVITY_TYPES };
